site_name: Prouecto de Softare - Guías 2020
theme: 'material'
nav:
  - Home: index.md
  - Comandos: commands.md
  - Ssh: ssh.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite

