site_name: Proyecto de Software 2021
theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.tabs.sticy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Inicio: index.md
  - Teorías: 
    - Listado: 01_teorias.md
    - Presentacion: 01_teorias/clase0/
  - Práctica: 02_practicas.md
  - Herramientas: 03_herramientas.md
  - Guías:
    - Comandos: guias/01_commands.md
    - Ssh: guias/02_ssh.md
    - Ssh Gitlab: guias/03_ssh_gitlab.md
    - Instalar Git: guias/04_instalar_git.md
    - Instalar Python: guias/05_instalar_python.md
    - Manejo de Paquetes: guias/06_manejo_de_paquetes.md
    - Entornos Virtuales: guias/07_entornos_virtuales.md
    - Merge Requests en Gitlab: guias/08_merge_request.md
    - Aplicación Base: guias/09_template.md
    - Guías de Estilo: guias/10_guias_de_estilo.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
